src/objects/Leaderboard__c.object
<CustomObject>
    <fields>
        <fullName>Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Score</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Leaderboard</relationshipLabel>
        <relationshipName>Leaderboard</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leaderboard</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Leaderboard</label>
    <nameField>
        <displayFormat>LD-{0000}</displayFormat>
        <label>Leaderboard ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaderboard</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Answers</relationshipLabel>
        <relationshipName>Survey_Answers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>10</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Answers</relationshipLabel>
        <relationshipName>Survey_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Answer</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Survey Answer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>QuestionType__c</fullName>
        <label>QuestionType</label>
        <picklist>
            <picklistValues>
                <fullName>Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Questions</relationshipLabel>
        <relationshipName>Survey_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TypeChoices__c</fullName>
        <description>A comma separated list of options for the question picklist</description>
        <label>TypeChoices</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Survey Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey_Question_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Survey_Answer__c</fullName>
        <label>Survey Answer</label>
        <referenceTo>Survey_Answer__c</referenceTo>
        <relationshipLabel>Survey Question Answers</relationshipLabel>
        <relationshipName>Survey_Question_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Question Answers</relationshipLabel>
        <relationshipName>Survey_Question_Answers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Survey Question Answer</label>
    <nameField>
        <displayFormat>SQA-{0000}</displayFormat>
        <label>Survey Question Answer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey_Target__c.object
<CustomObject>
    <fields>
        <fullName>Between_20_and_30_Collected__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Between 20 and 30 Collected</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Between_20_and_30_Target__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Between 20 and 30 Target</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Between_30_and_40_Collected__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Between 30 and 40 Collected</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Between_30_and_40_Target__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Between 30 and 40 Target</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Between_40_and_50_Collected__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Between 40 and 50 Collected</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Between_40_and_50_Target__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Between 40 and 50 Target</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Between_50_and_60_Collected__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Between 50 and 60 Collected</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Between_50_and_60_Target__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Between 50 and 60 Target</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Female_Collected__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Female Collected</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Female_Target__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Female Target</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <label>Location Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>10</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Male_Collected__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Male Collected</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Male_Target__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Male Target</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Over_60_Collected__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Over 60 Collected</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Over_60_Target__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Over 60 Target</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Targets</relationshipLabel>
        <relationshipName>Survey_Targets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Under_20_Collected__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Under 20 Collected</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Under_20_Target__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Under 20 Target</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey Target</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Survey Target ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SurveyStockController.cls
public with sharing class SurveyStockController {
	@RemoteAction
	public static Datetime ping() {
		return datetime.now();
	}
	
    @RemoteAction
    public static List<Survey__c> getSurveys(){
        return [SELECT Id, Name__c 
                FROM Survey__c ORDER 
                BY Name];
    }
    
    @RemoteAction
    public static List<Survey_Question__c> getSurveyQuestion(String surveyId){
        return [SELECT TypeChoices__c, Question__c, QuestionType__c, Id 
                FROM Survey_Question__c 
                WHERE Survey__c = :surveyId];
    }
    
    @RemoteAction
    public static API_SurveyTarget getTargets(String surveyId, String latitude, String longitude) {
        Survey_Target__c target = getTarget(surveyId, latitude, longitude);
        if(target != null){
            return TargetCalculator.getApiTarget(target);
        }
        
        return null;
    }
    
    @RemoteAction
    public static List<API_LeaderboardUser> getLeaderboardUsers(String surveyId){
        // get user survey counts
		AggregateResult[] userSurveys = [SELECT CreatedById, count(Id) SurveyCount FROM Survey_Answer__c WHERE Survey__c =: surveyId GROUP BY CreatedById];
		
		// get all user details
        List<API_LeaderboardUser> users = new List<API_LeaderboardUser>();
        for(Leaderboard__c user: [SELECT User__c, Score__c FROM Leaderboard__c WHERE Survey__c =: surveyId]) {
            User usr = [SELECT FirstName, LastName, Phone, Email, Id FROM User WHERE Id =: user.User__c LIMIT 1];
            
            // lookup answer count
			Integer surveyAnswers = 0;
			for(AggregateResult ar : userSurveys) {
				if(ar.get('CreatedById') == usr.Id){
					surveyAnswers = (Integer)ar.get('SurveyCount');
				}
			}
            
            users.add(new API_LeaderboardUser(usr.FirstName, usr.LastName, user.Score__c.round(), usr.Phone, usr.Email, surveyAnswers));
        }
        
        users.sort();       
        return users;
    }
    
    @RemoteAction
    public static void setSurveyAnswers(API_SurveyAnswers answers){
        // add contact and survey to db
        Contact contact = addContact(answers);
        addSurveyAnswers(answers, contact);
        Enums.Gender gender = TargetCalculator.getGender(answers.title);
        
        // calculate score for the survey
        Survey_Target__c target = getTarget(answers.surveyId, answers.latitude, answers.longitude);
        Decimal surveyValue = TargetCalculator.getGenderValue(target, gender) + TargetCalculator.getAgeValue(target, contact.Birthdate);
    
        // update leaderboard
        Leaderboard__c leaderboard = getLeaderboard(answers.surveyId);
        if(leaderboard == null){
            leaderboard = new Leaderboard__c();
            leaderboard.User__c = UserInfo.getUserId();
            leaderboard.Survey__c = answers.surveyId;
            leaderboard.Score__c = surveyValue;
        } else {
            leaderboard.Score__c = leaderboard.Score__c + surveyValue;
        }
        
        upsert leaderboard;
            
        // update target
        if(target != null) {
            target = TargetCalculator.setTargets(target, gender, contact.Birthdate);
            update target;
        }
    }
    
    private static Leaderboard__c getLeaderboard(String surveyId){
        List<Leaderboard__c> results = [SELECT User__c, Survey__c, Score__c, Id
                                        FROM Leaderboard__c
                                        WHERE Survey__c =: surveyId AND User__c =: UserInfo.getUserId()
                                        LIMIT 1];
        if(!results.isEmpty()){
            return results[0];
        }
        
        return null;
    }
    
    private static Contact addContact(API_SurveyAnswers answers){
        Contact contact = new Contact();
        contact.FirstName = answers.firstName;
        contact.LastName = answers.lastName;
        contact.MailingPostalCode = answers.postcode;
        contact.Birthdate = date.parse(answers.birthDate);
        contact.Title = answers.title;
        
        insert contact;
        
        return contact;
    }
    
    private static void addSurveyAnswers(API_SurveyAnswers answers, Contact contact){
        Survey_Answer__c sa = new Survey_Answer__c();
        sa.Contact__c = contact.Id;
        sa.Survey__c = answers.surveyId;        
            
        if(answers.latitude != null && answers.latitude.length() > 0 && answers.longitude != null && answers.longitude.length() > 0) {
            sa.Location__Latitude__s = decimal.valueOf(answers.latitude);
            sa.Location__Longitude__s = decimal.valueOf(answers.longitude);
        }
        
        insert sa;
        
        for(API_SurveyAnswers.Answer answer: answers.answers){
            Survey_Question_Answer__c qa = new Survey_Question_Answer__c();
            qa.Survey_Answer__c = sa.Id;
            qa.Survey_Question__c = answer.questionId;
            qa.Answer__c = answer.answer;
            
            insert qa;
        }
    }
    
    private static Survey_Target__c getTarget(String surveyId, String latitude, String longitude) {
        // attempt to find target based on location
        List<Survey_Target__c> results;
        if(latitude != null && latitude.length() > 0 && longitude != null && longitude.length() > 0) {
            String q = 'SELECT Location_Name__c, Under_20_Target__c, Under_20_Collected__c, Survey__c, Over_60_Target__c, Over_60_Collected__c,' +
                    'Male_Target__c, Male_Collected__c, Id, Female_Target__c, Female_Collected__c, Between_50_and_60_Target__c,' + 
                    'Between_50_and_60_Collected__c, Between_40_and_50_Target__c, Between_40_and_50_Collected__c, Between_30_and_40_Target__c,' + 
                    'Between_30_and_40_Collected__c, Between_20_and_30_Target__c, Between_20_and_30_Collected__c ' + 
                    'FROM Survey_Target__c WHERE Survey__c =: surveyId ' +          
                    'AND DISTANCE(Location__c, GEOLOCATION(' + latitude + ',' + longitude + '), \'mi\') < 20 ' +
                    'ORDER BY DISTANCE(Location__c, GEOLOCATION(' + latitude + ',' + longitude + '), \'mi\') LIMIT 1';
                    
            results = Database.query(q);        
            if(!results.isEmpty()){
                return results[0];
            }
        }
        
        // pull out the location free target
        results =   [SELECT Location_Name__c, Under_20_Target__c, Under_20_Collected__c, Survey__c, Over_60_Target__c, Over_60_Collected__c,
                    Male_Target__c, Male_Collected__c, Id, Female_Target__c, Female_Collected__c, Between_50_and_60_Target__c,
                    Between_50_and_60_Collected__c, Between_40_and_50_Target__c, Between_40_and_50_Collected__c, Between_30_and_40_Target__c,
                    Between_30_and_40_Collected__c, Between_20_and_30_Target__c, Between_20_and_30_Collected__c
                    FROM Survey_Target__c 
                    WHERE Survey__c =: surveyId
                    AND location__latitude__s = null
                    AND location__longitude__s = null
                    ORDER BY id
                    LIMIT 1];
        
        if(!results.isEmpty()){
            return results[0];
        }
        
        return null;
    }
}